CREATE DATABASE PIA_BDM;

use PIA_BDM;

select * from users;

delete  from categories;
select * from user_types;

select * from news;
select * from news_categories;
select * from news_status;
select * from key_words_news;
select * from multimedia;
select * from news_multimedia;

INSERT INTO news_status(STATUS,CREATED_BY,STATUS_ID) VALUES("EN REDACCION",117,1);
INSERT INTO news_status(STATUS,CREATED_BY,STATUS_ID) VALUES("TERMINADA",117,2);
INSERT INTO news_status(STATUS,CREATED_BY,STATUS_ID) VALUES("PUBLICADA",117,3);

select * from categories;

select * from multimedia;
select * from news_multimedia;
select * from comments;
select * from news_comments;

INSERT INTO user_types(USER_TYPES_ID,DESCRIPTION) VALUES (1,"Editor");
INSERT INTO user_types(USER_TYPES_ID,DESCRIPTION) VALUES (2,"Reportero");
INSERT INTO user_types(USER_TYPES_ID,DESCRIPTION) VALUES (3,"Usuario");

INSERT INTO users
(EMAIL, PASSWORD, NAME, LAST_NAME, USER_TYPES_ID)
VALUES
("editor@gmail.com", "#Test123", "Editor" , "Apellido", 1);

DELETE  FROM news_multimedia WHERE MULTIMEDIA_ID < 85;
DELETE FROM multimedia WHERE MULTIMEDIA_ID < 85;

CREATE VIEW NOTICIAS_PUBLICADAS AS
SELECT news.NEWS_ID, news.TITLE, news.LEAD_TEXT, news.CITY, news.STATE, news.COUNTRY, news.SIGNATURE, news.NEWS_TEXT,
news.DATE_OF_EVENTS, news.LIKES, news.CREATED_BY,news.PUBLISHED_DATE, news_multimedia.MULTIMEDIA_ID, CONCAT(users.NAME, ' ', users.LAST_NAME) AS REPORTER_NAME FROM news
INNER JOIN news_multimedia ON news.NEWS_ID = news_multimedia.NEWS_ID AND news.STATUS = 3 AND news.ACTIVE=1
INNER JOIN users ON users.USERS_ID = news.CREATED_BY;

SELECT * FROM NOTICIAS_PUBLICADAS;

SELECT NEWS_ID,CATEGORY_ID FROM news_categories where NEWS_ID = 145;

DELETE FROM news_categories where NEWS_ID = 145;
DELETE FROM key_words_news where NEWS_ID = 145;
DELETE FROM news_multimedia where NEWS_ID = 145;

SELECT * FROM news_multimedia;
SELECT * FROM multimedia;

CREATE VIEW NOTICIAS_TERMINADAS AS
SELECT news.NEWS_ID, news.TITLE, news.LEAD_TEXT, news.CITY, news.STATE, news.COUNTRY, news.SIGNATURE, news.NEWS_TEXT,
news.DATE_OF_EVENTS, news.LIKES, news.CREATED_BY,news.PUBLISHED_DATE, news_multimedia.MULTIMEDIA_ID FROM news
INNER JOIN news_multimedia ON news.NEWS_ID = news_multimedia.NEWS_ID AND news.STATUS = 2 AND news.ACTIVE=1;

CREATE VIEW NOTICIAS_EN_REDACCION AS
SELECT news.NEWS_ID, news.TITLE, news.LEAD_TEXT, news.CITY, news.STATE, news.COUNTRY, news.SIGNATURE, news.NEWS_TEXT,
news.DATE_OF_EVENTS, news.LIKES, news.CREATED_BY,news.PUBLISHED_DATE, news_multimedia.MULTIMEDIA_ID FROM news
INNER JOIN news_multimedia ON news.NEWS_ID = news_multimedia.NEWS_ID AND news.STATUS = 1 AND news.ACTIVE=1;

SELECT * FROM NOTICIAS_EN_REDACCION;
SELECT * FROM NOTICIAS_PUBLICADAS;
SELECT * FROM NOTICIAS_TERMINADAS GROUP BY NEWS_ID;
SELECT * FROM NOTICIAS_TERMINADAS;

SELECT NEWS_ID,TITLE,LEAD_TEXT,CITY,STATE,COUNTRY,SIGNATURE,NEWS_TEXT,DATE_OF_EVENTS, LIKES, CREATED_BY, PUBLISHED_DATE, MEDIA,IS_VIDEO
FROM NOTICIAS_COMPLETAS ORDER BY NEWS_ID DESC LIMIT 6;


DROP VIEW NOTICIAS_PUBLICADAS;


CREATE VIEW NOTICIAS_PUBLICADAS_COMPLETAS AS 
SELECT  NOTICIAS_PUBLICADAS.NEWS_ID, NOTICIAS_PUBLICADAS.TITLE, NOTICIAS_PUBLICADAS.LEAD_TEXT, NOTICIAS_PUBLICADAS.CITY,
 NOTICIAS_PUBLICADAS.STATE, NOTICIAS_PUBLICADAS.COUNTRY, NOTICIAS_PUBLICADAS.SIGNATURE, NOTICIAS_PUBLICADAS.NEWS_TEXT,
NOTICIAS_PUBLICADAS.DATE_OF_EVENTS, NOTICIAS_PUBLICADAS.LIKES, NOTICIAS_PUBLICADAS.CREATED_BY, NOTICIAS_PUBLICADAS.PUBLISHED_DATE, 
NOTICIAS_PUBLICADAS.MULTIMEDIA_ID, NOTICIAS_PUBLICADAS.REPORTER_NAME, multimedia.MEDIA, multimedia.IS_VIDEO FROM NOTICIAS_PUBLICADAS
INNER JOIN multimedia ON multimedia.MULTIMEDIA_ID = NOTICIAS_PUBLICADAS.MULTIMEDIA_ID;

SELECT * FROM NOTICIAS_PUBLICADAS_COMPLETAS;



SELECT NEWS_ID,TITLE,LEAD_TEXT,CITY,STATE,COUNTRY,SIGNATURE,NEWS_TEXT,DATE_OF_EVENTS, LIKES, CREATED_BY, PUBLISHED_DATE, MEDIA,IS_VIDEO
FROM NOTICIAS_COMPLETAS ORDER BY PUBLISHED_DATE  DESC LIMIT 6;

SELECT NEWS_ID,TITLE,LEAD_TEXT,CITY,STATE,COUNTRY,SIGNATURE,NEWS_TEXT,DATE_OF_EVENTS, LIKES, CREATED_BY, PUBLISHED_DATE, MEDIA,IS_VIDEO
FROM NOTICIAS_COMPLETAS GROUP BY NEWS_ID ORDER BY PUBLISHED_DATE  DESC LIMIT 3;

CALL sp_users("Login", null, "123@gmail.com", "1233$$%##TRT445s", null, null,null,null ,null , null,null ,null , null);

CALL sp_categories("InsertIntoNewsCategories",null,"Nacional","Amarillo", 2, null, null,null,null,null);

SELECT USERS_ID, CREATION_DATE FROM users ORDER BY USERS_ID DESC LIMIT 1;

SELECT NEWS_ID,TITLE,LEAD_TEXT,CITY,STATE,COUNTRY,SIGNATURE,NEWS_TEXT,DATE_OF_EVENTS, LIKES, CREATED_BY, PUBLISHED_DATE, MEDIA,IS_VIDEO
FROM NOTICIAS_COMPLETAS GROUP BY NEWS_ID ORDER BY PUBLISHED_DATE  DESC LIMIT 3;

SELECT NEWS_ID,TITLE,LEAD_TEXT,CITY,STATE,COUNTRY,SIGNATURE,NEWS_TEXT,DATE_OF_EVENTS, LIKES, CREATED_BY, PUBLISHED_DATE, MEDIA,IS_VIDEO
FROM NOTICIAS_COMPLETAS WHERE IS_VIDEO = 1 GROUP BY NEWS_ID ORDER BY PUBLISHED_DATE  DESC LIMIT 3;


insert INTO news_status(STATUS) values("PUBLICADA");


CALL sp_tags("Insert", "tagTest", null);


CREATE VIEW COMMENTS_BY_NEWS AS 
SELECT  comments.COMMENT_ID, comments.COMMENT_TEXT, comments.CREATED_BY, news_comments.NEWS_ID
FROM comments INNER JOIN news_comments on news_comments.COMMENT_ID = comments.COMMENT_ID; 

SELECT * FROM COMMENTS_BY_NEWS;

DROP VIEW COMMENTS_BY_NEWS;


CALL sp_comments("Insert",null, "comentario editor", 26 ,null,119,null );

SELECT NEWS_ID,TITLE,LEAD_TEXT,CITY,STATE,COUNTRY,SIGNATURE,NEWS_TEXT,DATE_OF_EVENTS, LIKES, CREATED_BY, PUBLISHED_DATE, MEDIA,IS_VIDEO
FROM NOTICIAS_COMPLETAS GROUP BY NEWS_ID ORDER BY PUBLISHED_DATE  DESC LIMIT 3;

CALL sp_news("SelectNewsById", 123, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
